# name this docker-compose.yaml
# run docker-compose up -d to build the file
# run docker-compose down to stop the containers
version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres_db_name
      POSTGRES_USER: postres_user
      POSTGRES_PASSWORD: postgres_pw
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
        #host machine port maps to container port
    ports:
      - '9432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadminemail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_pw
      PGADMIN_LISTEN_PORT:
        80
        #host machine port maps to container port
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - 'db:pgsql-server'
volumes:
  db-data:
  pgadmin-data:
